import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { QueryClientProviderWrapper } from '@/providers/query-client-provider';
import { ThemeProvider, themeInitScript } from '@/providers/theme-provider';
import { ToastProvider } from '@/providers/toast-provider';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Agencia Safira',
  description: 'Generated by Agencia Safira',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body>
        <ThemeProvider>
          <QueryClientProviderWrapper>
            <ToastProvider>{children}</ToastProvider>
          </QueryClientProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
